### ISSUE TITLE
Make file doesn't work

### ISSUE THREAD

**Issue by passelma42** [vgl-hub/gfastats#13]
Hi, 
I tried making the gitclone in winubuntu but it won't make:
![image](https://user-images.githubusercontent.com/73598059/159060430-989cf50f-8571-4198-abb4-631f63ac698c.png)
Build essentials and apt-install g++ also didn't work.

**Comment by gf777** [comment]
@passelma42 if you type g++ in the command line, does it work? If not, it's not installed (otherwise make should find it too)

**Comment by passelma42** [comment]
It was not installed before. I installed it later, but make didn't work then either...

**Comment by gf777** [comment]
so if you type
`g++`
in the command line you see some output? That error simply saying that g++ is not in your path so I'd be surprised if it was correctly installed

**Comment by passelma42** [comment]
Hi Giulio, 
-------
Thanks for your response. I've put g++ in my path, Although /usr/bin was already there.
-------
(base) passelma@we11c255:~/winubu/gfastats$ which g++
/usr/bin/g++

(base) passelma@we11c255:~/winubu/gfastats$ echo $PATH | grep 'g++'
/home/passelma/miniconda3/bin:/home/passelma/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_2004.2022.1.0_x64__79rhkp1fndgsc:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Users/Administrator/AppData/Local/Microsoft/WindowsApps:/mnt/c/Windows/system32/tools:/mnt/c/Anaconda3:/mnt/c/Anaconda3/Scripts:/mnt/c/Program Files/PuTTY:/mnt/c/Program Files (x86)/Calibre2:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Users/passelma/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/passelma/AppData/Roaming/PAUP4:/mnt/c/Users/passelma/AppData/Local/Programs/Git/cmd:/snap/bin:/usr/bin/g++
-------
Running g++, finds the program
-------
(base) passelma@we11c255:~/winubu/gfastats$ g++
g++: fatal error: no input files
compilation terminated.
-------
making the program gets me this error, pointing to line 16 in the Makefile
-------
(base) passelma@we11c255:~/winubu/gfastats$ make
mkdir -p build/bin
g++ -g -Wall -std=gnu++11 -O3 -I./include -I./zlib -o build/bin/gfastats src/gfastats.cpp -lz
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make: *** [Makefile:16: gfastats] Error 1

**Comment by angebrajuka** [comment]
looks like you have to install zlib, this might help: https://stackoverflow.com/questions/3373995/usr-bin-ld-cannot-find-lz
