### ISSUE TITLE
multiple threads

### ISSUE THREAD

**Issue by George-du** [vgl-hub/gfastats#31]
Dear Giulio,
      How to use gfastats software with multiple threads?
      I'm looking forward to your reply.
Best,
       Du

**Comment by gf777** [comment]
Hi Du,

sorry for the late reply. Gfastats will automatically detect the threads available in your machine and try to use them all. You can also specify a number with the `--threads` or `-j` option.

Hope this helps!

**Comment by George-du** [comment]
Dear Giulio,

Thanks for your useful reply.

Best,
Du
