### ISSUE TITLE
command not found: gfstats

### ISSUE THREAD

**Issue by coliverbrown** [vgl-hub/gfastats#33]
Hello,
I recently downloaded the latest release of gfastats. However, when I tried to run `gfastats -h` on Terminal, I got the error "command not found". Is there another step after downloading the most recent release to get gfastats to work? For reference, I am using Terminal on Mac.
Thanks

**Comment by gf777** [comment]
hi @coliverbrown 

Once you have compiled a binary, you will either have to move it to a folder under your PATH, add the folder where it is to your PATH, or using the relative/absolute path to it (in the case of gfastats `build/bin/gfastats`.
