### ISSUE TITLE
Could we use it to calculate pan-genome?

### ISSUE THREAD

**Issue by ld9866** [vgl-hub/gfastats#37]
Hello software developer!
Thank you for developing such a good software. 
At present, we would like to count some indicators of the pan-genome we have built, including Nodes, Edges and Reference nodes,Non-reference nodes, Node length, Length of non-reference nodes, Length of small (&lt; Length of non-reference nodes, length of small (&lt; 50 bp) non-reference nodes, Length of large (&gt; 50 bp) non-reference nodes.

Could we use your software to analyze the gfa files we generate?
Merry Christmas!

**Comment by gf777** [comment]
hi @ld9866,

Gfastats has been designed to evaluate/manipulate gfa files, primarily for assembly graphs. We used it in a few applications for pangenomes but not many so far. We obviously count the nodes and edges but do not assume the presence of a selected reference so far. I suspect these new metrics you need would be relatively easy to implement. I wonder if it would make more sense as a new `pangfastats` branch though. Food for thought for 2023.

Happy holidays!

**Comment by ld9866** [comment]
Thank you for your patient reply!
Hope your software is getting better and better!
Best wishes
Happy holidays
