### ISSUE TITLE
add read mapping option to gfastats?

### ISSUE THREAD

**Issue by maxmaronna** [vgl-hub/gfastats#46]
Hello,
Is it possible to add a read mapping strategy (ex, backmap or merqury) to gfastats? I think it would be very useful to evaluate assembly correctness.

Cheers
maxmaronna

**Comment by gf777** [comment]
Hi @maxmaronna 
Many thanks for reaching out!
It would be extremely interesting to know/discuss which specific features would be more useful. Note that we have two separate tools dedicated to analyzing reads alignments to the graph and kmers (which generates QV estimates as in Merqury):
https://github.com/vgl-hub/gfalign (alignment)
https://github.com/vgl-hub/kreeq (kmer)
Happy holidays
