### ISSUE TITLE
gap length

### ISSUE THREAD

**Issue by ksc289** [vgl-hub/gfastats#49]
Good morning,
I have used gfastats to analyze some metrics of a de novo genome assembly, it has been very useful!
But I have a question about gaps, from what length of N does gfastats consider there to be a gap?

Thank you very much,
Karen :)

**Comment by gf777** [comment]
Hi Karen! @ksc289 
Glad to hear it. Even just a 1 bp N will be considered a gap, ie. contigs can only be made of ACGT bases
All the best
Giulio

**Comment by ksc289** [comment]
Hi Giulio,
thank you very much for the reply!

Karen
