### ISSUE TITLE
bioconda requires more files created during release

### ISSUE THREAD

**Issue by Smeds** [vgl-hub/gfastats#50]
I plan to update the conda recipe to include the latest version of gfastats available on Bioconda. To do this, I'll need a downloadable tar.gz or zip file of the repository that includes the gfalibs submodule. Unfortunately, the tar.gz file generated during the release process does not contain this submodule."

Would it be possible for someone to upload a similar files as with the previous release [1.3.6](https://github.com/vgl-hub/gfastats/releases/tag/v1.3.6)? In that release, we can find the following additional files:
 - https://github.com/vgl-hub/gfastats/releases/download/v1.3.6/gfastats.v1.3.6.tar.gz
 -  https://github.com/vgl-hub/gfastats/releases/download/v1.3.6/gfastats.v1.3.6.zip

**Comment by gf777** [comment]
yes, will add next week

**Comment by Smeds** [comment]
great!

**Comment by gf777** [comment]
Hi @Smeds 
This should achieve what you want: https://github.com/vgl-hub/gfastats/releases/tag/v1.3.8
(the -with_submodule source code)
