### ISSUE TITLE
can it rename contigs in gff file 

### ISSUE THREAD

**Issue by gunjanpandey** [vgl-hub/gfastats#51]
can it rename contigs in a gff file?

**Comment by gf777** [comment]
hi @gunjanpandey can you be more specific, i.e. provide an example of what you'd like to achieve?

**Comment by gunjanpandey** [comment]
for example the contig IDs for all haplotypes in a *.gff start with h1tg. Wondering if your program allows renaming h1tg to something else. It can, however, be done with awk.

**Comment by gf777** [comment]
yes, it sounds like something you want to do with a regex editor!
Feel free to come back with other suggestions
