### ISSUE TITLE
Error when running gfastats version 1.3.8

### ISSUE THREAD

**Issue by SaimMomin12** [vgl-hub/gfastats#52]
Hi @gf777,

I am in the process of updating the gfastats tool in Galaxy from version 1.3.6 to 1.3.8. The following command, which worked without issues in version 1.3.6, now throws an error in version 1.3.8:

`gfastats dataset_02.fasta --seq-report --tabular > test03.tabular`

The error message is as follows:

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
Aborted (core dumped)
```

I would appreciate any guidance on resolving this issue.

Thank you!

**Comment by gf777** [comment]
hi @SaimMomin12 
good catch! Since v1.3.7 --sequence-report was replaced by --segment-report. Btw --tabular shouldn't add anything here, it's tabular either way..
I've added a guard for unrecognized short and long options so that this will be easier to catch in the future
